const students=[{name:"Gabriel Santos",reg:"2026-0712",class:"7º A",status:"active",guardian:"Juliana Santos"},{name:"Mariana Alves",reg:"2026-0818",class:"8º A",status:"active",guardian:"Ricardo Alves"},{name:"Lucas Ferreira",reg:"2026-0634",class:"6º A",status:"active",guardian:"Ana Ferreira"},{name:"Beatriz Lima",reg:"2026-0902",class:"9º A",status:"pending",guardian:"Carla Lima"},{name:"Pedro Rocha",reg:"2026-0827",class:"8º A",status:"active",guardian:"Márcio Rocha"}];
const teachers=[["Camila Andrade","Matemática","8º A · 9º A"],["Rafael Nunes","Português","6º A · 7º A"],["Juliana Moraes","História","7º A · 8º A"],["Eduardo Reis","Ciências","6º A · 7º A"],["Fernanda Costa","Geografia","8º A · 9º A"],["Paulo Mendes","Inglês","6º A · 9º A"]];
const subjects=[["MAT","Matemática","Camila Andrade"],["POR","Português","Rafael Nunes"],["HIS","História","Juliana Moraes"],["CIE","Ciências","Eduardo Reis"],["GEO","Geografia","Fernanda Costa"],["ING","Inglês","Paulo Mendes"]];
const grades=[{name:"Mariana Alves",g:[8.5,9,8,9.2]},{name:"Pedro Rocha",g:[6.5,7.2,6.8,7.5]},{name:"Ana Clara",g:[9.2,8.8,9.4,9]},{name:"João Victor",g:[5.8,6.3,6,6.7]},{name:"Sofia Martins",g:[7.8,8.1,7.5,8.4]}];
let studentFilter="all";const titles={dashboard:"Visão geral",students:"Alunos",teachers:"Professores",enrollments:"Matrículas",subjects:"Disciplinas",calendar:"Calendário",grades:"Notas & Boletins"};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$$(".nav").forEach(b=>b.onclick=()=>{const id=b.dataset.view;$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav").forEach(n=>n.classList.toggle("active",n===b));$("#pageTitle").textContent=titles[id]});$$("[data-jump]").forEach(b=>b.onclick=()=>document.querySelector('[data-view="'+b.dataset.jump+'"]').click());
function renderStudents(){const rows=students.filter(s=>studentFilter==="all"||s.status===studentFilter);$("#studentRows").innerHTML=rows.map(s=>`<tr><td>${s.name}</td><td>${s.reg}</td><td>${s.class}</td><td><span class="status">${s.status==="active"?"Ativo":"Pendente"}</span></td><td>${s.guardian}</td><td>•••</td></tr>`).join("")}$$("[data-student-filter]").forEach(b=>b.onclick=()=>{$$("[data-student-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");studentFilter=b.dataset.studentFilter;renderStudents()});
$("#teacherGrid").innerHTML=teachers.map(t=>`<article class="person-card"><div class="avatar">${t[0].split(" ").map(x=>x[0]).slice(0,2).join("")}</div><h3>${t[0]}</h3><p><b>${t[1]}</b><br>${t[2]}</p></article>`).join("");$("#subjectGrid").innerHTML=subjects.map(s=>`<article class="subject-card"><div class="code">${s[0]}</div><h3>${s[1]}</h3><p>Professor: ${s[2]}</p></article>`).join("");
const lanes=[["Documentação",["Gabriel Santos","Lívia Souza"]],["Conferência",["Arthur Lima","Helena Costa"]],["Contrato",["Daniel Rocha"]],["Concluída",["Marina Lopes","Caio Nunes"]]];$("#enrollmentPipeline").innerHTML=lanes.map(l=>`<div class="lane"><h3>${l[0]} · ${l[1].length}</h3>${l[1].map(n=>'<div class="enroll-card"><b>'+n+'</b><span>Matrícula 2026</span></div>').join("")}</div>`).join("");
const events={5:"Reunião pedagógica",10:"Conselho de classe",14:"Início das avaliações",25:"Reunião de responsáveis"};let cells="";for(let i=27;i<=30;i++)cells+=`<div class="day muted"><b>${i}</b></div>`;for(let d=1;d<=31;d++)cells+=`<div class="day"><b>${d}</b>${events[d]?'<span class="event">'+events[d]+'</span>':""}</div>`;$("#calendarGrid").innerHTML=cells;
function renderGrades(){$("#gradeRows").innerHTML=grades.map((r,ri)=>{const avg=(r.g.reduce((a,b)=>a+b,0)/4).toFixed(1);return `<tr><td>${r.name}</td>${r.g.map((g,gi)=>'<td><input class="grade-input" data-ri="'+ri+'" data-gi="'+gi+'" type="number" min="0" max="10" step=".1" value="'+g+'"></td>').join("")}<td>${avg}</td><td class="${avg>=7?"approved":"attention"}">${avg>=7?"Aprovado":"Atenção"}</td></tr>`}).join("");$$(".grade-input").forEach(i=>i.onchange=()=>{grades[+i.dataset.ri].g[+i.dataset.gi]=Math.max(0,Math.min(10,+i.value));renderGrades()})}
const studentModal=$("#studentModal"),enrollmentModal=$("#enrollmentModal");function open(m){m.classList.add("open")}function close(m){m.classList.remove("open")}$("#newStudentBtn").onclick=()=>open(studentModal);$("#newEnrollmentBtn").onclick=()=>open(enrollmentModal);$("#quickBtn").onclick=()=>open(studentModal);$$("[data-close]").forEach(b=>b.onclick=()=>close(b.closest(".modal")));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)close(m)});
$("#studentForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);students.unshift({name:f.get("name"),reg:"2026-"+String(Math.floor(Math.random()*9000+1000)),class:f.get("class"),status:"active",guardian:f.get("guardian")});renderStudents();e.currentTarget.reset();close(studentModal);toast("Aluno cadastrado")};$("#enrollmentForm").onsubmit=e=>{e.preventDefault();close(enrollmentModal);e.currentTarget.reset();toast("Matrícula criada e enviada para conferência")};
$("#newTeacherBtn").onclick=()=>toast("Cadastro de professor em evolução");$("#newSubjectBtn").onclick=()=>toast("Cadastro de disciplina em evolução");$("#newEventBtn").onclick=()=>toast("Novo evento acadêmico em evolução");$("#closeReportsBtn").onclick=()=>{if(confirm("Fechar boletins da turma selecionada?")){$("#pendingReports").textContent="0";toast("Boletins fechados com sucesso")}};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("daegonEducaTheme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("daegonEducaTheme")==="dark")document.body.classList.add("dark");function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
const command=$("#command"),cmd=$("#commandInput");function renderCommand(){const q=cmd.value.toLowerCase();const items=[...Object.entries(titles).map(([id,label])=>({label,run:()=>document.querySelector('[data-view="'+id+'"]').click()})),...students.map(s=>({label:s.name,run:()=>document.querySelector('[data-view="students"]').click()})),...teachers.map(t=>({label:t[0],run:()=>document.querySelector('[data-view="teachers"]').click()}))].filter(x=>x.label.toLowerCase().includes(q));$("#commandResults").innerHTML=items.map((x,i)=>'<button class="command-item" data-ci="'+i+'">'+x.label+'</button>').join("");$$("[data-ci]").forEach(b=>b.onclick=()=>{items[+b.dataset.ci].run();command.classList.remove("open")})}$("#searchBtn").onclick=()=>{command.classList.add("open");renderCommand();cmd.focus()};cmd.oninput=renderCommand;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();command.classList.add("open");renderCommand();cmd.focus()}if(e.key==="Escape"){$$(".modal").forEach(close);command.classList.remove("open")}});renderStudents();renderGrades();